### ISSUE TITLE
Not Eligible Error

### ISSUE THREAD

**Issue by Dunkhaun** [FailedTrades/BloxFlip-Bot#3]
Keeps telling me I am not Eligible for some reason

**Comment by PePeTheReno** [comment]
Change the id on all of the commands to yours
Ex:
[`if BuyerRoleId in ctx.author.roles or ctx.author.id == idhere:`](https://github.com/FailedTrades/BloxFlip-Bot/blob/V-1.0-BUG-FIXES/main.py#L106)
Or create a buyer role then copy it's id and paste it here
https://github.com/FailedTrades/BloxFlip-Bot/blob/V-1.0-BUG-FIXES/main.py#L13

**Comment by FailedTrades** [comment]
BuyerRoleId = your roles id
ctx.author.id == ur userid
